version: '3'
services:
  ap-main:
    container_name: ap-main
    build: ./ap-main
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    volumes:
      - ./ap-main:/usr/src/express
  ap-signaling:
    container_name: ap-signaling
    build: ./ap-signaling
    environment:
      NODE_ENV: development
    ports:
      - '3001:3000'
    volumes:
      - ./ap-signaling:/usr/src/express
  web:
    container_name: web
    image: nginx
    volumes:
      - ./web/logs/:/var/log/nginx/
      - ./web/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
      - "443:443"
  db:
    container_name: db
    image: mysql:5.7.22
    ports:
      - "3306:3306"
    hostname: dbserver
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: test
        MYSQL_PASSWORD: test
        MYSQL_DATABASE: test
